function products() {
  return [
    {
      id: "1",
      imgUrl: "/img/1.png",
      name: "Nike Supreme Neon",
      price: 6110,
    },
    {
      id: "2",
      imgUrl: "/img/2.png",
      name: "Air Urbans",
      price: 3371,
    },
    {
      id: "3",
      imgUrl: "/img/3.png",
      name: "Nike Eons ",
      price: 5294.5,
    },
    {
      id: "4",
      imgUrl: "/img/4.png",
      name: "Runners Highs",
      price: 2250,
    },
    {
      id: "5",
      imgUrl: "/img/5.png",
      name: "Nike Reactive",
      price: 3333,
    },
    {
      id: "6",
      imgUrl: "/img/6.png",
      name: "Nike Aesthetics",
      price: 4853,
    },
    {
      id: "7",
      imgUrl: "/img/7.png",
      name: "Skateboarders White",
      price: 1500,
    },
    {
      id: "8",
      imgUrl: "/img/8.png",
      name: "Puma Csual Black",
      price: 999,
    },
    {
      id: "9",
      imgUrl: "/img/9.png",
      name: "High Supreme",
      price: 1125,
    },
    {
      id: "10",
      imgUrl: "/img/10.png",
      name: "Nike HighRise - Red",
      price: 3120,
    },
    {
      id: "11",
      imgUrl: "/img/11.png",
      name: "Retro Camo",
      price: 920,
    },
    {
      id: "12",
      imgUrl: "/img/12.png",
      name: "Nike HighRise - Yello",
      price: 220,
    },
    {
      id: "13",
      imgUrl: "/img/13.png",
      name: "Eon Nike",
      price: 5220,
    },
    {
      id: "14",
      imgUrl: "/img/14.png",
      name: "Nike Air",
      price: 3920,
    },
    {
      id: "15",
      imgUrl: "/img/15.png",
      name: "Neo Nike",
      price: 4420,
    },
    {
      id: "16",
      imgUrl: "/img/16.png",
      name: "All Star Neon",
      price: 1120,
    },
    {
      id: "17",
      imgUrl: "/img/17.png",
      name: "FIAS Molten Series",
      price: 2220,
    },
    {
      id: "18",
      imgUrl: "/img/18.png",
      name: "Nike Flight",
      price: 1220,
    },
    {
      id: "19",
      imgUrl: "/img/19.png",
      name: "Puma Aesthetic",
      price: 2820,
    },
    {
      id: "20",
      imgUrl: "/img/20.png",
      name: "Nike Runner",
      price: 2990,
    },
    {
      id: "21",
      imgUrl: "/img/21.png",
      name: "Nike HighTech",
      price: 9999,
    },
    {
      id: "22",
      imgUrl: "/img/22.png",
      name: "Puma Rainbow",
      price: 5634,
    },
    {
      id: "23",
      imgUrl: "/img/23.png",
      name: "Nike Jams",
      price: 6973,
    },
    {
      id: "24",
      imgUrl: "/img/24.png",
      name: "Nike essential - Brown",
      price: 3999,
    },
    {
      id: "25",
      imgUrl: "/img/25.png",
      name: "Addida Zebra",
      price: 2988,
    },
    {
      id: "26",
      imgUrl: "/img/26.png",
      name: "Charcoal",
      price: 899,
    },
    {
      id: "27",
      imgUrl: "/img/27.png",
      name: "Nike Shoot",
      price: 3420,
    },
    {
      id: "28",
      imgUrl: "/img/28.png",
      name: "Addidas Essential",
      price: 1220,
    },
    {
      id: "29",
      imgUrl: "/img/29.png",
      name: "Addidas Daily's",
      price: 2220,
    },
    {
      id: "30",
      imgUrl: "/img/30.png",
      name: "Skethers Champ",
      price: 3220,
    },
    {
      id: "31",
      imgUrl: "/img/31.png",
      name: "Puma b&w",
      price: 2499,
    },
    {
      id: "32",
      imgUrl: "/img/32.png",
      name: "Nike Velvet",
      price: 999,
    },
    {
      id: "33",
      imgUrl: "/img/33.png",
      name: "Nike Sand",
      price: 1299,
    },
    {
      id: "34",
      imgUrl: "/img/34.png",
      name: "Nike USA Original",
      price: 4923,
    },
    {
      id: "35",
      imgUrl: "/img/35.png",
      name: "'Nike retro Jam",
      price: 1100,
    },
    {
      id: "36",
      imgUrl: "/img/36.png",
      name: "Nike Jump",
      price: 2568,
    },
    {
      id: "37",
      imgUrl: "/img/37.png",
      name: "Nike AirForce",
      price: 8999,
    },
    {
      id: "38",
      imgUrl: "/img/38.png",
      name: "Addidas Bubble Gums",
      price: 999,
    },
    {
      id: "39",
      imgUrl: "/img/39.png",
      name: "Puma Camo",
      price: 1499,
    },
    {
      id: "40",
      imgUrl: "/img/40.png",
      name: "Supreme Camo",
      price: 3923,
    },
    {
      id: "41",
      imgUrl: "/img/41.png",
      name: "CHY Fast",
      price: 999,
    },
    {
      id: "42",
      imgUrl: "/img/42.png",
      name: "CHY Essentials",
      price: 699,
    },
    {
      id: "43",
      imgUrl: "/img/43.png",
      name: "Retro Neon",
      price: 434,
    },
    {
      id: "44",
      imgUrl: "/img/45.png",
      name: "Reebok Jump",
      price: 2444,
    },
    {
      id: "46",
      imgUrl: "/img/46.png",
      name: "FAST Dino",
      price: 2000,
    },
    {
      id: "47",
      imgUrl: "/img/47.png",
      name: "Nike Surfs",
      price: 4999,
    },
  ];
}
export default products;
